### ISSUE TITLE
UC16 - Recarregar os dados da extensão

### ISSUE THREAD

**Issue by guilhermegoa** [ICEI-PUC-Minas-PPLES-TI/plf-es-2022-1-tcci-5308100-dev-arthur-rocha-guilherme-oliveira#19]
Como desenvolvedor, desejo recarregar os dados da extensão.

**Comment by ArthurRAmaral** [comment]
- https://stackoverflow.com/questions/71644360/add-a-button-to-viewcontainer-that-is-always-visible-in-vscode-extension
- https://code.visualstudio.com/api/extension-guides/tree-view#view-actions
